# Generated by Django 5.2.5 on 2025-08-14 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemovie',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='title',
        ),
        migrations.AlterField(
            model_name='movierating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
